services:
  twitch-streamer:
    build: twitch-streamer
    env_file: ".env"
    cap_add:
      - SYS_ADMIN
    environment:
      - DISPLAY=:99
      - SCREEN_GEOMETRY=1920x1080x24

  diplomacy:
    build: ai_animation
    ports:
      - "4173:4173"
      - "5173:5173"
