services:
  twitch-streamer:
    build: twitch-streamer
    env_file: ".env"
    cap_add:
      - SYS_ADMIN
    environment:
      - DISPLAY=:99
    ports:
      - "9222:9222"

  diplomacy:
    build: ai_animation
    ports:
      - "4173:4173"
      - "5173:5173"
  diplomacy-dev:
    build: ai_animation
    ports:
      - "4173:4173"
      - "5173:5173"
    command: ["npm", "run", "dev-all"]
    volumes:
      - "./ai_animation/:/app/"
